@server = http://localhost
@port = 3000
@resource = api
@url = {{server}}:{{port}}/{{resource}}

###############################################

// Test: Get all users.
// Expected HTTP response status code: 200.
GET {{url}}/users

###############################################

// Test: Get all posts.
// Expected HTTP response status code: 200.
GET {{url}}/users/annaandersson/posts HTTP/1.1
content-type: application/json

{
   "debug": true
}

###############################################

// Test: Get a user that exists.
// Expected HTTP response status code: 200.
GET {{url}}/users/annaandersson HTTP/1.1
content-type: application/json

{
   "password": "annapass"
}

###############################################

// Test: Get a user that does not exists
// Expected HTTP response status code: 404.
GET {{url}}/users/khurre HTTP/1.1
content-type: application/json

{
   "password": "khurre123"
}

###############################################

// Test: Create (POST) a user.
// Expected HTTP response status code: 201.
POST {{url}}/users HTTP/1.1
content-type: application/json

{
   "userName": "limalm",
   "name": "Li Malm",
   "email": "limalm@gmail.com",
   "password": "li123"
}

###############################################

// Test: Get a post that exists.
// Expected HTTP response status code: 200.
GET {{url}}/posts/1

###############################################

// Test: Get a post that does not exists
// Expected HTTP response status code: 404.
GET {{url}}/posts/khurre

###############################################

// Test: Create (POST) a post.
// Expected HTTP response status code: 201.
POST {{url}}/posts HTTP/1.1
content-type: application/json

{
   "content": "Test test",
   "user": 3
}

###############################################

// Test: Create (POST) a post with a user that does not exist.
// Expected HTTP response status code: 400.
POST {{url}}/posts HTTP/1.1
content-type: application/json

{
   "content": "Bla bla",
   "user": 5000
}

###############################################

// Test: Like a post with an existing user & post.
// Expected HTTP response status code: 201.
POST {{url}}/posts/like/1 HTTP/1.1
content-type: application/json

{
   "user": 3
}

###############################################

// Test: Like a post with an non-existing user/post..
// Expected HTTP response status code: 400.
POST {{url}}/posts/like/400 HTTP/1.1
content-type: application/json

{
   "user": 300
}

###############################################

// Test: Dislike an existing post.
// Expected HTTP response status code: 201.
POST {{url}}/posts/dislike/1 HTTP/1.1
content-type: application/json

{
   "user": 4
}

###############################################

// Test: Dislike a non-existing post.
// Expected HTTP response status code: 400.
POST {{url}}/posts/dislike/450 HTTP/1.1
content-type: application/json

{
   "user": 477
}
###############################################

// Test: Update (PATCH) a post.
// Expected HTTP  response status code: 200.
PATCH  {{url}}/posts/12 HTTP/1.1
content-type: application/json

{
   "content": "Ändrar lite här.",
   "user": 10
}

###############################################

// Test: Update (PATCH) a non-existing post.
// Expected HTTP  response status code: 404.
PATCH  {{url}}/posts/1077 HTTP/1.1
content-type: application/json

{
   "content": "Ändrar lite här.",
   "user": 10
}
###############################################

// Test: Delete a post that exists.
// Expected HTTP response status code: 204.
DELETE {{url}}/posts/12

###############################################

// Test: Delete a post that does not exist.
// Expected HTTP response status code: 404.
DELETE {{url}}/posts/500

###############################################

// Test: Delete a like.
// Expected HTTP response status code: 204.
DELETE {{url}}/posts/like/1 HTTP/1.1
content-type: application/json

{
   "user": 1
}

###############################################

// Test: Delete a dislike.
// Expected HTTP response status code: 204.
DELETE {{url}}/posts/dislike/1 HTTP/1.1
content-type: application/json

{
   "user": 1
}

###############################################
