@server = http://localhost
@port = 3000
@resource = api
@url = {{server}}:{{port}}/{{resource}}

###############################################

// Test: Get all users.
// Expected HTTP response status code: 200.
GET {{url}}/users

###############################################


// Test: Get all posts.
// Expected HTTP response status code: 200.
GET {{url}}/posts

###############################################

// Test: Get a user that exists.
// Expected HTTP response status code: 200.
GET {{url}}/users/Test

###############################################

// Test: Get a user that does not exists
// Expected HTTP response status code: 404
GET {{url}}/users/fail

###############################################

// Test: Post (add) a user.
// Expected HTTP response status code: 201.
POST {{url}}/users HTTP/1.1
content-type: application/json

{
    "userName": "mina",
    "name": "Mina",
    "email": "mina@hej.com",
    "password": "mina123"
}

###############################################

// Test: Delete a post.
// Expected HTTP response status code: 200.
DELETE {{url}}/posts/1

###############################################


// Test: Add a new post.
// Expected HTTP response status code: 200.
POST {{url}}/posts HTTP/1.1
content-type: application/json
{
   "content": "Test test",
   "user": 1,
   "likes": 15,
   "dislikes": 3
}

###############################################

// Test: Get neighborhood with all restaurants.
// Expected HTTP response status code: 200.
GET {{url}}/neighborhoods/Brooklyn

###############################################

// Test: Get all neighborhoods with all restaurants.
// Expected HTTP  response status code: 200.
GET {{url}}/all